
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: video_library
  pool: 5
  username: root
  password:
  host: 127.0.0.1


test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: video_library
  pool: 5
  username: root
  password:
